AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GitHub OIDC Deployment Policy

Parameters:
  RoleName:
    Description: Name of the IAM Role for the inline policy
    Type: String

Resources:
  Role:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref RoleName
      PolicyName: DeploymentPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - serverlessrepo:*
            Resource: "*"
