# Reference: https://github.com/repository-settings/app

_extends: .github

repository:
  name: platform-agg-metadata
  description: Metadata writer for mytiki.com managed data catalogs
  homepage: https://mytiki.com/platform/aggregation
  topics: aggregation, catalog, metadata
  private: false
  has_projects: true
  has_discussions: false
  has_issues: true

teams:
  - name: sysadmin
    permission: admin
  - name: engineering
    permission: push
  - name: product
    permission: triage
  - name: backend
    permission: push

environments:
  - name: production

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - Analyze java-kotlin

milestones:
  - title: 0.2.1
    description: |
      DRAFT
    state: open
