version = 0.1

[default.global.parameters]
stack_name = "core-ocean-metadata-function"
region = "us-east-2"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
disable_rollback = true
no_fail_on_empty_changeset = true
no_execute_changeset = true

[default.validate.parameters]
lint = true

[prod.global.parameters]
region = "us-east-2"
s3_bucket = "mytiki-sam-deploy"
s3_prefix = "core/ocean/metadata/function"

[prod.deploy.parameters]
no_execute_changeset = false

[dev.global.parameters]
region = "us-east-2"
s3_bucket = "mytiki-sam-deploy-CREATE-DEV-BUCKET"
s3_prefix = "core/ocean/metadata/function"

[dev.deploy.parameters]
no_execute_changeset = false
