version = 0.1
[default.deploy.parameters]
stack_name = "ocean-metadata"
resolve_s3 = true
s3_prefix = "ocean/metadata"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
