AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ocean - Catalog Infrastructure

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: com.mytiki.ocean.App::handleRequest
      Runtime: java17
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 20
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            BatchSize: 10
            Queue: !GetAtt Queue.Arn

  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ocean-catalog.fifo
      ContentBasedDeduplication: true
      DeduplicationScope: messageGroup
      FifoQueue: true

Outputs:
  Function:
    Description: "ARN"
    Value: !GetAtt Function.Arn

  Queue:
    Description: "ARN"
    Value: !GetAtt Queue.Arn
