AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ocean-Metadata Lambda Function

Parameters:
  QueueArn:
    Description: Arn for the SQSEvent Queue
    Type: String
  BucketName:
    Description: The S3 bucket name for the lake
    Type: String
  DatabaseName:
    Description: The Glue database name
    Type: String

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../..
      Handler: com.mytiki.ocean.metadata.App::handleRequest
      Runtime: java17
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 20
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            FunctionResponseTypes:
              - ReportBatchItemFailures
            BatchSize: 10
            Queue: !Ref QueueArn
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BucketName
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - glue:GetTable
                - glue:GetTables
              Resource:
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/${DatabaseName}"
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/${DatabaseName}/*"

Outputs:
  Arn:
    Value: !GetAtt Function.Arn
