AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ocean-Metadata SQS Queue

Parameters:
  QueueName:
    Type: String
    Default: ocean-catalog
    Description: The name of the FIFO Queue.

Resources:
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${QueueName}.fifo"
      ContentBasedDeduplication: true
      DeduplicationScope: messageGroup
      FifoQueue: true

Outputs:
  Arn:
    Value: !GetAtt Queue.Arn
