AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ocean - Metadata Infrastructure

Resources:
  Queue:
    Type: AWS::Serverless::Application
    Properties:
      Location: queue.yml

  Function:
    Type: AWS::Serverless::Application
    Properties:
      Location: function.yml
      Parameters:
        QueueArn: !GetAtt [Queue, Outputs.Arn]
