---
name: CICD

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
          cache: maven
          cache-dependency-path: |
            pom.xml
            utils/pom.xml

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Lint Java code
        run: make lint-code

      - name: Build and test Java code
        run: make build-code

      - name: Upload Java test results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: target/surefire-reports/**/*.xml

      - name: Lint infra code
        run: make lint-infra

      - name: Build infra code (synthesize)
        run: make build-infra

      - name: Upload build artifacts (SAM build)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: sam-build-output
          path: .aws-sam/

  Analyze:
    runs-on: ubuntu-22.04
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 20
          distribution: zulu
          cache: maven
          cache-dependency-path: |
            pom.xml
            utils/pom.xml

      - name: Install deps
        run: make build-utils

      - name: Initialize
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Analysis
        uses: github/codeql-action/analyze@v3

  # TODO:
  # - Move this to another workflow and trigger based on tag
  # - Deploy pushes to main to dev env
  # - Tags go to prod
  Deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    needs:
      - Build
      - Analyze
    environment: Production
    permissions:
      id-token: write
      contents: write
    env:
      ENVIRONMENT: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false
          sparse-checkout: |
            Makefile
            template.yml
            samconfig.toml
          sparse-checkout-cone-mode: false

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: sam-build-output

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubDeployCoreOceanMetadata
          role-session-name: ${{ vars.SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy via SAM CLI
        run: make deploy
